### ISSUE TITLE
How to generate the readme gif with different text

### ISSUE THREAD

**Issue by bayrem-gharsellaoui** [mmphego/mmphego#3]
Hi, there.

First of all cool readme, I really liked the simplicity and the design,
I was wondering if I can generate a readme with different text.
Thanks in advance

Bayrem

**Comment by mmphego** [comment]
Hi,
Thanks for showing interest in my readme.

I just mangled the js code from this blog site: [view-source:https://cyris.io/#line390](view-source:https://cyris.io/#line390) 

Good luck,
Mpho
